libraryDependencies += "org.scala-lang.modules"     %% "scala-parser-combinators"  % "1.0.6"
libraryDependencies += "io.circe"                   %% "circe-core"                % "0.8.0"
libraryDependencies += "org.scalatest"              %% "scalatest"                 % "3.0.3"  % "test"
libraryDependencies += "org.scalacheck"             %% "scalacheck"                % "1.13.5" % "test"
libraryDependencies += "io.circe"                   %% "circe-parser"              % "0.8.0"  % "test"
